### ISSUE TITLE
使用spring的@Validated注解时启动报空指针导致项目启动不起来

### ISSUE THREAD

**Issue by Rachelaave** [shenjingwaa/relax#2]
当我在controller上使用@Validated时会空指针导致项目启动不起来，我debug看是扫描时候没有扫到@RelaxClass这个注解，作者可以看看

**Comment by shenjingwaa** [comment]
好的,我这几天找时间改进一下这个地方.

**Comment by shenjingwaa** [comment]
欧了,改进了已经
